project:
  type: website

website:
  title: "Object-Oriented Programming and Software Engineering"

  sidebar:
    smooth-scroll: true
    logo: img/logo.png
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Welcome
      - plan.qmd
      - section: "Using `git`"
        contents:
        - href: wp_gitgithub/shell.qmd
        - href: wp_gitgithub/git.qmd
        - href: wp_gitgithub/exercises.qmd
      - section: "Object-Oriented thinking"
        contents:
        - href: wp_oop/oop.qmd
      - section: "Implementation"
        contents:
        - href: wp_vicsek/implement.qmd
      - section: "C++ to Python interface with `pybind11`"
        contents:
        - href: wp_pybind/interface.qmd
      - section: "Wrapping and improvements"
        contents:
        - href: wp_wrapping/pyclasses.qmd



format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true
    number-chapters: true
    # number-sections: true