project:
  type: website


website:
  title: "Object-Oriented Programming and Software Engineering"
  sidebar:
    smooth-scroll: true
    logo: img/logo.png
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - plan.qmd
      - section: "1| Software Engineering"
        contents:
        - href: wp_gitgithub/shell.qmd
        - href: wp_gitgithub/git.qmd
        - href: wp_gitgithub/github.qmd
        - href: wp_gitgithub/make.qmd
        - href: wp_gitgithub/exercises.qmd
      - section: "2| Object-Oriented thinking"
        contents:
        - href: wp_oop/oop.qmd
        - href: wp_oop/complete-design.qmd
        - href: wp_oop/solutions.qmd
      - section: "3| Implementation"
        contents:
        - href: wp_vicsek/implement.qmd
        - href: wp_vicsek/solutions.qmd
      - section: "4| C++ to Python interface"
        contents:
        - href: wp_pybind/pythonoop.qmd
        - href: wp_pybind/interface.qmd
        - href: wp_pybind/solutions.qmd
    #   - section: "5| Wrapping"
    #     # contents:
        # - href: wp_wrapping/pyclasses.qmd



format:
  html:
    theme: cosmo
    grid:
      sidebar-width: 305px
    # css: styles.css
    toc: true
    number-chapters: true
    # number-sections: true
