---
title: "Solutions"
html:
output-file: solutions.html
---

The solutions to the **C++ to Python interface** workshop can be downloaded as a git bundle from here:

- [📒 CppToPython.bundle](../bundles/CppToPython.bundle)

## How to use the bundle

First, download the bundle and clone it locally on you machine with

```bash
git clone CppToPython.bundle
```

Then you will be able to see all the branches and commits of the bundle.

In particular, an easy way to navigate the solutions is to use the tags: the bundle contains so-called `git` tags, which are shortcuts to commits. You can see all the tags by typing

```bash
git tag
```

inside your cloned repository.


You have two main parts for this workshop:

- The tasks of *Wrap C++ in a Python object* are labelled `4.x` where x is the number of the task (x is 1 or 2)
- The tasks of *Using C++ objects from Python* are labelled `4.x` where x is the number of the task (x is 3 to 7)

To access the state of the repository for a particular task just use `git checkout <task-number>`. So, for example, to access task 4 

```bash
git checkout 4.1
```

You can always go back to the main branch with

```bash
git checkout main
```